package com.glenncai.cursormirrorsync.config

import com.google.gson.Gson
import com.intellij.openapi.diagnostic.Logger
import java.io.File
import com.glenncai.cursormirrorsync.core.models.ConnectionInfo
import com.glenncai.cursormirrorsync.core.managers.ConfigFileExceptionClassifier
import com.glenncai.cursormirrorsync.core.managers.ConfigFileContext
import com.glenncai.cursormirrorsync.core.managers.ConfigFileValidator
import com.glenncai.cursormirrorsync.core.exceptions.*

/**
 * Reads connection information from .cursor-mirror-sync.json files
 */
class ConnectionFileReader {

    companion object {
        private const val CONNECTION_FILE_NAME = ".cursor-mirror-sync.json"
        private val log = Logger.getInstance(ConnectionFileReader::class.java)
    }

    private val gson = Gson()
    private val exceptionClassifier = ConfigFileExceptionClassifier()
    private val configValidator = ConfigFileValidator()

    /**
     * Reads connection information from the project root directory with enhanced error handling
     */
    fun readConnectionFile(projectPath: String?): ConnectionInfo? {
        if (projectPath.isNullOrBlank()) {
            log.info("Project path is null or empty")
            return null
        }

        val connectionFile = File(projectPath, CONNECTION_FILE_NAME)
        val filePath = connectionFile.absolutePath

        // First, validate the file
        val validationResult = configValidator.validateConfigFile(filePath)

        if (!validationResult.isValid) {
            // Log validation errors
            validationResult.errors.forEach { error ->
                log.warn("Configuration validation error: $error")
            }
            // Provide suggestions to user (but don't auto-fix)
            validationResult.suggestions.forEach { suggestion ->
                log.info("Suggestion: $suggestion")
            }
            return null
        }

        return try {
            val fileContent = connectionFile.readText()
            val context = createContext(connectionFile, fileContent)

            val connectionInfo = gson.fromJson(fileContent, ConnectionInfo::class.java)

            if (connectionInfo.isValid()) {
                log.info("Successfully read connection info from: $filePath")
                log.info("Port: ${connectionInfo.port}, Project: ${connectionInfo.projectName}")

                connectionInfo.createdAt?.let {
                    log.info("Connection file created at: $it")
                }
                connectionInfo.lastModified?.let {
                    log.info("Last modified at: $it")
                }
                connectionInfo.lastActiveAt?.let {
                    log.info("Last active at: $it")
                }

                log.info(connectionInfo.getGenerationInfo())
                connectionInfo
            } else {
                // Create validation exception for invalid connection info
                val validationException = ConfigValidationException(
                    message = "Invalid connection info in file: $filePath",
                    configKey = "connectionInfo",
                    configValue = connectionInfo,
                    validationErrors = connectionInfo.validate()
                )

                log.warn(validationException.getFormattedMessage())
                log.warn("Port: ${connectionInfo.port}, ProjectName: '${connectionInfo.projectName}', ProjectPath: '${connectionInfo.projectPath}'")
                log.warn("Please check the connection file format. Required fields: port, projectName, projectPath")
                log.warn("Optional fields: status, createdAt, lastModified, lastActiveAt, _utcTime")
                log.warn("⚠️  This file should be auto-generated by VSCode extension. Manual editing is not recommended.")
                null
            }

        } catch (e: Exception) {
            // Use intelligent exception classification
            val context = createContext(connectionFile, "")
            val configException = exceptionClassifier.classifyException(e, context)

            log.error("Failed to read connection file: ${configException.getFormattedMessage()}", configException)

            // Provide specific error guidance based on exception type
            when (configException) {
                is ConfigParsingException -> {
                    log.error("Connection file has invalid JSON format. Line: ${configException.lineNumber}, Column: ${configException.columnNumber}")
                    log.error("Parse error: ${configException.parseError}")
                }
                is ConfigFileNotFoundException -> {
                    log.error("Connection file not found. VSCode extension may not be running.")
                    log.error("Search paths: ${configException.searchPaths}")
                }
                is ConfigFileCorruptedException -> {
                    log.error("Connection file appears to be corrupted. Type: ${configException.corruptionType}")
                    // JetBrains IDE should NEVER restore or modify connection files
                    // Only VSCode should create and manage .cursor-mirror-sync.json files
                    log.info("Connection file is corrupted - waiting for VSCode to recreate it")
                }
                is ConfigPermissionException -> {
                    log.error("Permission denied accessing connection file. Operation: ${configException.operation}")
                    log.error("Required permissions: ${configException.requiredPermissions}")
                }
                else -> {
                    log.error("Unexpected error reading connection file: ${configException.message}")
                }
            }

            null
        }
    }

    /**
     * Creates context for exception classification
     */
    private fun createContext(file: File, content: String): ConfigFileContext {
        return ConfigFileContext(
            filePath = file.absolutePath,
            fileName = file.name,
            fileSize = if (file.exists()) file.length() else 0,
            operation = "read",
            expectedFormat = "JSON",
            fileContent = content,
            contentPreview = if (content.length > 100) content.take(100) + "..." else content,
            canRead = file.canRead(),
            canWrite = file.canWrite(),
            isDirectory = file.isDirectory(),
            requiredFields = listOf("port", "projectName", "projectPath")
        )
    }

    /**
     * Gets configuration file processing statistics
     */
    fun getStatistics(): String {
        return buildString {
            appendLine("=== ConnectionFileReader Statistics ===")
            appendLine(configValidator.getStatistics())
        }
    }

    /**
     * Resets configuration file processing statistics
     */
    fun resetStatistics() {
        configValidator.resetStatistics()
    }

    /**
     * Validates a connection file without reading it
     */
    fun validateConnectionFile(projectPath: String?): Boolean {
        if (projectPath.isNullOrBlank()) {
            return false
        }

        val connectionFile = File(projectPath, CONNECTION_FILE_NAME)
        val validationResult = configValidator.validateConfigFile(connectionFile.absolutePath)

        return validationResult.isValid
    }


}
